name: Print env and ARG_MAX test

on:
  workflow_dispatch:

jobs:
  print-env:
    runs-on: [ubuntu-latest]
    steps:
      - run: printenv
      - run: getconf ARG_MAX
      - run: |
          export CHECK_RUNS=$(cat check_runs.json)
          printenv
