name: Print env and ARG_MAX test

on:
  workflow_dispatch:

jobs:
  print-env:
    name: Print environment information
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - run: printenv

      - run: getconf ARG_MAX

      - run: |
          export CHECK_RUNS=$(cat check_runs.json)
          printenv
